### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by WimDeMeester** [AstroKeith/eFinder64#1]
Hi @AstroKeith,

Thanks a lot for the easy installation instructions.  Everything seemed to work without problems.  I have two small problems:

- In the Readme, you write that you have to use 

`/venv-efinder/bin/python ~/Solver/eFinderVNCGUI.py run`

to run the eFinder manually, but the first / should be removed.

- Is it possible to bring back the main_eF.py file for the old wiring scheme?  If it is OK for you, I can make a pull request for that.  
- I guess a small script to update the code to the latest version would also be a nice improvement.

**Comment by AstroKeith** [comment]
Thanks Wim, well spotted on the rogue '/'.
I've edited the readme and uploaded the old wiring handbox.
I'm working on an update script - a good idea. Do you think just update the whole /Solver contents and the autostart desktop file? I've drafted something at update.sh on the GitHub which should do it. I'll test tomorrow but if you have any comments!...

**Comment by WimDeMeester** [comment]
Thanks for re-adding the old wiring!  I'll test this tomorrow.
I don't know about yet how everything is installed, but is executing 

`git pull`

in the Solver directory not enough to do the update?

Another hint.  In the README.md page, you can put a backquote as first and last character of the line with the python command.  You will then see the command in a nice code block.

**Comment by AstroKeith** [comment]
Thanks for the hints!
First time I had ever heard of a backquote! Nice.
`git pull` dosent work I'm afraid

**Comment by WimDeMeester** [comment]
Hi @AstroKeith ,
Thanks for adding the old main.py file.  Tested today and all seems to be fine.
